export const users = [
  {
    id: '1',
    email: 'nuttapong.p@nextzy.com',
    firstName: 'Nuttapong',
    lastName: 'Phisitbutr',
    nickname: 'Nut',
    bio: 'Rookie Web Dev',
    status: 'Happy',
    profileImage: 'https://api.dicebear.com/7.x/personas/svg?seed=Steven',
  },
  {
    id: '2',
    email: 'leomessi@nextzy.com',
    firstName: 'Lionel',
    lastName: 'Messi',
    nickname: 'Leo',
    bio: 'Footballer',
    status: 'Happy',
    profileImage: 'https://api.dicebear.com/7.x/personas/svg?seed=John',
  },
  {
    id: '3',
    email: 'cr7@nextzy.com',
    firstName: 'Cristiano',
    lastName: 'Ronaldo',
    nickname: '',
    bio: 'Footballer',
    status: 'Happy',
    profileImage: 'https://api.dicebear.com/7.x/personas/svg?seed=Michael',
  },
];
